export const SERVICE_PACKS = [
  {
    id: 'starter',
    name: 'Pack Starter',
    icon: 'globe',
    color: '#06B6D4',
    standardPrice: 790,
    launchPrice: 490,
    recurringLabel: 'Maintenance : 79 €/mois',
    description: 'Un site vitrine professionnel, mobile-first et prêt à générer des contacts.',
    features: ['3 à 5 pages', 'Formulaire et WhatsApp', 'SEO de base', 'Google Business Profile'],
    publicStatus: 'draft',
  },
  {
    id: 'business',
    name: 'Pack Business',
    icon: 'trending-up',
    color: '#D4AF37',
    standardPrice: 1790,
    launchPrice: 990,
    recurringLabel: 'Suivi : 99 à 149 €/mois',
    popular: true,
    description: 'Un système d’acquisition complet avec site, chatbot, CRM et automatisations.',
    features: ['Jusqu’à 8 pages', 'Chatbot de qualification', 'CRM prospects', 'Séquences email'],
    publicStatus: 'draft',
  },
  {
    id: 'automation',
    name: 'Pack Automation',
    icon: 'zap',
    color: '#8B5CF6',
    standardPrice: 2990,
    launchPrice: 1490,
    recurringLabel: 'Supervision : 199 €/mois',
    description: 'Des workflows et tableaux de bord conçus pour supprimer les tâches répétitives.',
    features: ['Analyse des processus', 'Workflows sur mesure', 'Dashboard', 'WhatsApp et email'],
    publicStatus: 'draft',
  },
  {
    id: 'ia-premium',
    name: 'Pack IA Premium',
    icon: 'cpu',
    color: '#EC4899',
    standardPrice: 5900,
    standardPricePrefix: 'Dès',
    launchPriceLabel: 'Sur devis',
    recurringLabel: 'Accompagnement : dès 399 €/mois',
    description: 'Une plateforme métier complète avec agents IA, espace client et pilotage avancé.',
    features: ['Agents IA spécialisés', 'Espace client sécurisé', 'Cockpit complet', 'Support prioritaire'],
    publicStatus: 'draft',
  },
];

export const HAINOFLOW_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    color: '#06B6D4',
    monthlyPrice: 19,
    yearlyPrice: 190,
    bundledMonthlyPrice: 17,
    target: 'Indépendants et petites activités',
    features: ['Factures et devis', 'Facturation structurée', 'Relances simples', 'Export comptable'],
    publicStatus: 'draft',
  },
  {
    id: 'pro',
    name: 'Pro',
    color: '#D4AF37',
    monthlyPrice: 39,
    yearlyPrice: 390,
    bundledMonthlyPrice: 35,
    target: 'PME et facturation récurrente',
    features: ['Tout Starter', 'Factures récurrentes', 'Relances automatisées', 'Portail et suivi client'],
    publicStatus: 'draft',
  },
  {
    id: 'business',
    name: 'Business',
    color: '#8B5CF6',
    monthlyPrice: 79,
    yearlyPrice: 790,
    bundledMonthlyPrice: 69,
    target: 'Équipes et automatisations avancées',
    features: ['Tout Pro', 'Workflows avancés', 'API et intégrations', 'Support prioritaire'],
    publicStatus: 'draft',
  },
];

export function formatEuro(value) {
  return new Intl.NumberFormat('fr-BE', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 0,
  }).format(value);
}
